# Generated by Django 5.1.3 on 2024-11-30 00:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialcategory",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Material Categories",
            },
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="myapp.materialcategory",
            ),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
