# Generated by Django 5.1.3 on 2024-12-02 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_materialcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="materialconsumption",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="materialdelivery",
            options={
                "ordering": ["-delivery_date"],
                "verbose_name_plural": "Material Deliveries",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="material",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="material",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="materialconsumption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="materialdelivery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="materialconsumption",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="materialdelivery",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning Phase"),
                    ("ONGOING", "Ongoing"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PLANNING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MaterialSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_subcategories",
                        to="myapp.materialcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Material Subcategories",
                "ordering": ["category__name", "name"],
            },
        ),
    ]
