# Generated by Django 5.1.3 on 2024-12-02 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_material_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["category", "subcategory", "name"]},
        ),
        migrations.AddField(
            model_name="material",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.materialsubcategory",
            ),
        ),
    ]
