# Generated by Django 5.1.3 on 2024-12-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_project_code_remove_project_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="code",
        ),
        migrations.AddField(
            model_name="warehouse",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouses",
                to="myapp.project",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
